### ISSUE TITLE
80-byte source authentication is a big problem

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#81]
The current design where the sender "countersign" it's own AEAD creates 80-byte source authentication when everything except CCM_8 is used. E.g. AES-CCM, AES-GCM, and ChaCha20-Poly1305.  This make Group OSCORE impossible to use in many situations such as the 75 bytes in some cellular network broadcast (even with CCM_8).
 
It would be very strange to force people wanting to use AES-CCM, AES-GCM, or ChaCha20-Poly1305 or other 16-bit tag algorithms in pair-wise to use 80-byte source authentication, when it can trivially by done with 64 bytes. While the TLS conclusions regarding CCM_8 is misleading, I think there will be a trend toward 128 bit tags. Many deployments for government and financial institutions always use 128 bit tags.

Another big disadvantage with the current design is that the user to chose between more useless in the signature mode and less security in pair-wise. In the signature mode, the tag provides no security and you want as small as possible. For pair-wise many application would definitly want to use 16 bytes tags, e.g. application aligning with the CSNA suite.

8-16 additional bytes overhead for the signature mode makes a big difference. Group OSCORE without the useless AEAD tag could be used, but Group OSCORE with the tag cannot.

**Comment by cabo** [comment]
I agree with the reasoning above, but have a question anyway:
Is the AEAD authenticator actually "useless"?  Doesn't it protect against DoSing the signature verifier?

**Comment by marco-tiloca-sics** [comment]
This issue was also addressed in version -12, by admitting that the group mode could also use an encryption algorithm without integrity tag as Signature Encryption Algorithm.

If an encryption algorithm with integrity tag is used anyway, the tag does not help against a DoS based on inducing the message recipient to verify a bad signature. As also clarified in version -12 [1][2], the signature verification must happen and be successfully completed before proceeding with the decryption of the COSE object.


[1] https://datatracker.ietf.org/doc/html/draft-ietf-core-oscore-groupcomm-12#section-8.2
[2] https://datatracker.ietf.org/doc/html/draft-ietf-core-oscore-groupcomm-12#section-8.4

**Comment by chrysn** [comment]
>  Is the AEAD authenticator actually "useless"? Doesn't it protect against DoSing the signature verifier?

The verifier could check the AEAD tag on the encrypted part first. The text says that "The server MUST perform signature verification before decrypting the COSE object" (with exceptions only for those that can't), but that's not ruling out verification of the tag. (Granted, many cryptographic APIs don't support doing these things separately).

(Obtaining a valid tag on an encrypted signature is probably as easy or hard as obtaining a valid tag on the encrypted payload -- once an attacker has that, and either can be used to pester the server until the client's request on that seqno gets through and the obtained tag is burned).

**Comment by marco-tiloca-sics** [comment]
As per the follow-up side discussion, no further text is needed.
